#+TITLE:  A history of Daiwa Ryu, Dentokan  and Hakko Ryu jujutsu in the UK
#+SUBTITLE: A traditional martial arts club in Oxfordshire, UK.
#+DESCRIPTION: A personal view of the history of these martial arts in the UK. 


In about 1984, Roy Jerry Hobbs moved to Suffolk as his
latest posting with the United States Air Force.  Before that he had
been posted in Japan where he had pursued his passion for martial arts
with vigour.  As a result of this he had been awarded the grade of
shihan in [[http://www.hakkoryu.com][Hakko Ryu Jujutsu]].


On arrival in Suffolk, he started teaching Hakko Ryu jujutsu and
soon established a thriving class.  On being posted back to the States
a few years later, the club was able to continue to train under the
guidance of the senior students, with visits from both Jerry and
Garcia sensei, another Hakko Ryu shihan, based in Belgium.


Although invaluable, the limited contact with Hakko Ryu shihans might
not have been sufficient to allow the senior students to continue to
learn and enthuse the classes left in their care.  Here good fortune
stepped in.  One of the senior students at the club, Reg Siger,
discovered the Japanese Shitenoji boarding school near Bury St Edmunds
was starting a jujutsu class for the general public.  Three of us went
along, not knowing what to expect.  To our surprise we met Harada
sensei and Tanaka sensei, both retired Hakko Ryu shihan, now teaching
a similar style: Daiwa Ryu.  For the next few years we travelled over
to Shitenoji every Monday night and had the strange experience of
training in a kyudo dojo set amongst traditional Japanese buildings,
with a half timbered Suffolk farm house in the background. Along the
way Tanaka sensei granted permission to Reg, Richard and myself to
teach Daiwa Ryu jujutsu.  By this time Harada sensei had been reposted
to Austria by the Shitenoji school.  His story continues [[file:jigenryu.org][elsewhere]].

Following the death of the founder of Hakko Ryu jujutsu, his son
inherited the position of Nidai Soke.  The change of leadership
produced some upheaval amongst some of the senior shihans in the
organisation, resulting in a number of them leaving the Hakko Ryu and
establishing their own organisations.  Hobbs sensei set up the [[http://www.dentokanhombu.com][Kokusai
Dentokan Renmei]] in 1994.  No longer being affiliated with the Hakko
Ryu hombu, the clubs in the UK renamed themselves Dentokan Jujutsu.
The jujutsu taught continued as before, based heavily on the
techniques of Hakko Ryu jujutsu, with a strong influence from Daiwa
Ryu.


In 2013 I amicably parted ways with the Dentokan; the route they were
following was different to the one I was on and by then I was Dentokan
in name only.  I'm now teaching Daiwa Ryu in [[file:../classdetails/index.org][Warborough, Oxfordshire]].

