#+TITLE: Jujutsu, jujitsu, what's the difference?

#+BEGIN_EXPORT html

<div class="menu">
<a href='/'>Home</a><br>
<a href='/classdetails/'> Class details</a><br>
<a href='/blog/'>Blog</a>
</div>
#+END_EXPORT



* Jujutsu, Jujitsu - what's the difference?

Jujutsu, jujitsu, jiu jitsu --- there's a wide range of spellings
used to describe this Japanese martial art.  The problem is that, in
its native Japanese, none of these spellings are used.  Instead the
word is written using kanji, ideograms of
Chinese origins.  To translate these into the western alphabet used in
the English language requires a series of somewhat arbitrary
decisions.

The current standard for this translation provides us with jujutsu
--- the spelling adopted on this website.  But back in the first half of
the twentieth centry, jiujitsu and then jujitsu were preferred.  As
this corresponded to a period of wider awareness of Japanese martial
arts in the West, these earlier spellings have stuck in many
places.

As a quick check to see how common the various spellings are, I
used Google to count the number of occurrences of
each on the web.  As of 28 Nov 2002, the figures were:

|-----------+--------|
| jiu jutsu | 94,300 |
| jujitsu   | 81,000 |
| ju jitsu  | 52,900 |
| ju jutsu  | 51,700 |
| jujutsu   | 51,300 |
| jiujutsu  | 11,600 |
|-----------+--------|


So there is no obvious agreement on either the spelling or where the
word breaks --- absent in Japanese --- should be placed.

